### ISSUE TITLE
Connection Setup

### ISSUE THREAD

**Issue by ramyagarapati** [shipcod3/canTot#3]
I am trying to use this canTot tool with raspberry pi. I am using 2 way CAN connectors to communicate with both target and raspberry pi, so that I can see messages from canTot in my CANalyzer simulation. After starting the UDS fuzzer, I am not able to see any messages in the CANalyzer. Not sure why these messages are not reaching the target. Need help with connection setup

**Comment by shipcod3** [comment]
Have you tried sending messages using cansend at first and check if there are messages being sent?

**Comment by ramyagarapati** [comment]
Unfortunately that is also failing. It seems issue with my raspberry pi setup itself. Let me troubleshoot
